version: '3.8'
services:

  frontend:
    image: evgetta/foodgram_front:v1.0
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: evgetta/foodgram_back:v1.0
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value:
